### ISSUE TITLE
jquery error/warning caused by Atheos-MarkdownPreview

### ISSUE THREAD

**Issue by clach04** [Atheos/Atheos#103]
**Describe the bug**

Seeing jquery not found error in console.log in browser:

    public/pluginsJS.min.js:10

**To Reproduce**
1. Go to main page
2. open console  in web browser
3. look for errors

**Desktop (please complete the following information):**
 - OS: Windows (Server Linux)
 - Browser Firefox Developer
 - Version 79.0b9 (64-bit)

**Additional context**
Atheos headrevs from git - commit dba88b5eea2d020c2de1fcb055c26a5654c7fbf6
 Tue Jul 7 22:57:33 2020

**Comment by HLSiira** [comment]
What plugins do you have installed? I haven't had much time in updating the plugins from Codiad to Atheos and Atheos no longer has jQuery installed, but I'm more than willing to update a plugin if requested.

**Comment by clach04** [comment]
I actually need to open at least two plugin related tickets. I had at the time of the message:

* Atheos-Beautify-master
* Atheos-MarkdownPreview-master
* Plugin-Template-master

I previously had Beautify installed (not Atheos-Beautify-master) and I've removed Plugin-Template-master. I'm happy to remove all (and also pull down a different branch, I'm currently running out of master)

**Comment by HLSiira** [comment]
I bet it's the markdownpreview. I mentioned in the other ticked but some of the plugins that the marketplace lists aren't actually done being updated yet and since nobody has really asked for them specifically, it hasn't been high on my priority list.

I'll try to see if I can get that plugin updated in the next few weeks to work but I'd recommend only installing plugins listed in the built in Marketplace as it has a stronger vetting system for plugins.

**Comment by clach04** [comment]
Yep, with that plugin removed no errors.

No hurry, its something I'd like to use when its ready.
