### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by clach04** [Atheos/Atheos#104]
https://www.atheos.io/docs/installation appears to be the latest docs, I can not locate the source code for this.

https://github.com/Atheos/Atheos/blob/master/docs/INSTALL.txt appears to be the old docs (config.php no longer needs to be created manually).

I was going to add a note about ZIP module but not sure where to get the source to make that suggestion - I think this is needed for the integrated plugin/market system (which I'm not sure is supported at this time).

**Comment by HLSiira** [comment]
The source code the docs is in the gh-pages branch on the repo, or at least should be. I'm currently trying to rewrite the documentation site so it might not be there.

That install.txt is indeed old and honestly probably should be removed since I would rather have an external documentation site.

The market place is supported as much as I can and that is indeed where I think the zip module is sort of used, but it's also used when downloading a folder.

**Comment by clach04** [comment]
Thanks, that was it https://github.com/Atheos/Atheos/blob/gh-pages/content/docs/installation/index.md :-)

**Comment by clach04** [comment]
> The source code the docs is in the gh-pages branch on the repo, or at least should be. I'm currently trying to rewrite the documentation site so it might not be there.
> 
> That install.txt is indeed old and honestly probably should be removed since I would rather have an external documentation site.

Cool, PR posted for that.

> The market place is supported as much as I can and that is indeed where I think the zip module is sort of used, but it's also used when downloading a folder.

My installation has php zip (and it does allow zip plugins to be downloaded - it did not before hand) but downloading a folder gives me a tar.gz so I've not documented that piece. PR posted :)

**Comment by HLSiira** [comment]
The documentation of Atheos is my weakness right now honestly. Atheos has been so completely rewritten that maintaining documentation has become nearly impossible due to how fast Atheos changed during the past few months. Now though, development is slowing down and the codebase is becoming a lot more stable so I'll be spending more time documenting how these components and modules work on the website.

Let me know if you have any questions, I'm more than happy to answer or explain anything you come across, thank you for finding these.

**Comment by clach04** [comment]
Is the release cycle for pushing updated docs manual? https://www.atheos.io/docs/installation is showing old docs? Not urgent, this is an FYI/clarification.

**Comment by HLSiira** [comment]
I have to pull it to the server, which I forgot to do
