### ISSUE TITLE
Marketplace plugin loads Codiad marketplace

### ISSUE THREAD

**Issue by clach04** [Atheos/Atheos#107]
**Describe the bug**

Plugin download works but list is limited, for example includes Beautify plugin, not Atheos-Beautify-master.

**To Reproduce**
1. Bring up RIght hand side bar
2. Click on marketplace
3. do not see https://www.atheos.io/market (I've not debugged what/where its pulling from)

**Expected behavior**
Expecting https://www.atheos.io/market and Atheos plugin list

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows (Server Linux)
 - Browser Firefox Developer
 - Version 79.0b9 (64-bit)

**Additional context**
Atheos headrevs from git - commit dba88b5eea2d020c2de1fcb055c26a5654c7fbf6
 Tue Jul 7 22:57:33 2020

**Comment by HLSiira** [comment]
I'm willing to go on a limb and say that it's not loading the Codiad marketplace and is instead loading a much shorter list of plugins than the list on the Atheos website. It's might an undocumented/unfinished behavior of the marketplace.

Each plugin has a a JSON entry that contains a lot of information and one of the keys is the status of the plugin, which the Atheos website ignores. It lists them all regardless; however the actual built in marketplace only shows active/compatible plugins, since while I have plans to add a lot of plugins myself, I haven't had time to do so and I don't want someone to install a plugin that doesn't work.

I need to change it to convey that intent in the design, maybe graying out but still listing plugins that are under active development / planned.

It could also be a bad cached marketplace. Atheos caches it's market place requests in a json file in the data/cache folder so my server doesn't get hit with a new request every time you open the IDE. It refreshes about once a week but maybe there is an error in there somehow.

**Comment by clach04** [comment]
Makes sense, happy to close. Progressing #108
