### ISSUE TITLE
Plugins not working

### ISSUE THREAD

**Issue by clach04** [Atheos/Atheos#108]
**Describe the bug**

I suspect the right hand bar/menu/settings is supposed to list plugins, and it is not doing that.

I can see Beautify under settings but the Beautify when saving JS  doesn't do anything and atl-alt-b selects all the text (or highlights in in blue) but does not prettify/indent

**To Reproduce**
See above

**Expected behavior**
Expecting list of plugins (not sure if this is the expected behavior).

Also expecting indentation changes to this test.js file:

var c = 0;
        var i = 0;
    
    if (i) {
    console.log('jel');    
            console.log('lo');    
    }

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows (Server Linux)
 - Browser Firefox Developer
 - Version 79.0b9 (64-bit)

**Additional context**
Atheos headrevs from git - commit dba88b5eea2d020c2de1fcb055c26a5654c7fbf6
 Tue Jul 7 22:57:33 2020

I need help debugging.

I briefly debugged the Codiad  Beautify plugin, it was failing to load the js due to wrong path (tried hacking, by removing leading `/` in init.js for `atheos.Beautify` elements `path`, `controller`, and `dialog` which resolved that error but did not resolve plugin not showing up). I've since removed that and only used Atheos plugins.

NOTE my Atheos URL is: http://192.168.11.85:82/Atheos/ so **not** the root directory.

**Comment by HLSiira** [comment]
Each plugin decides if it needs or wants a right hand sidebar entry or not, Beautify is one of the plugins that doesn't need a sidebar entry since it doesn't have a need for a separate custom window, like a color picker or the git interface does. It simply has an entry for the settings manager and tacks onto the settings window.

I am wondering if maybe your plugins.min.js file in the public folder didn't refresh/rebuild and while you have the plugin installed, it isn't being sent to the client perhaps?

The beautify plugin is all client side, so if it's not working, it shouldn't be a URL / location issue, but I have some ideas on how that could be affecting it. The beautify plugin sends a request for the beautification scripts upon initialization and maybe it's not finding them due to the install location but you would see failed 404 requests in the browser console.

I'm assuming you mean you're pressing Ctrl + Alt + B and not both Alts and B; but it is highlighting everything blue? That's a pretty strong sign that the beautify plugin is running client sign but failing to get the beautification scripts. Are there any errors in the console?

**Comment by HLSiira** [comment]
Looked through the beautify code and it didn't support non root installations of Atheos. I fixed it in the latest push and should work now, I did a fresh install on non-root and installed the beautify plugin and worked with the test you supplied.

**Comment by clach04** [comment]
Thanks! Sadly this has the loading issue (but my previous fix won't work), console shows:

    Loading failed for the <script> with source “http://192.168.11.85:82/Atheos/undefinedplugins/Beautify/libs/beautify-css.js”.

repeated for all the lib *js files.

the settings page is showing up, but as expected ctrl-alt-B does nothing (as the js is not loaded).

Anything I need to do browser (or server) side to flush things to be really sure? I wiped out the plugin dir and restarted the webserver (and refreshed browser).

Not sure if this is relevant but marketplace still offers me the option (+) to add beautify  even though it was installed a few minutes ago. Also the thing (link?) to the right of the blue plus sign is not clickable for any items in the marketplace).

![image](https://user-images.githubusercontent.com/424032/88442114-1e13f880-cdc8-11ea-93cf-6fc8f7212439.png)

**Comment by clach04** [comment]
I'm using php 7.0 (see #99 for specifics). Not sure if this is an issue but mentioning for completeness.

**Comment by HLSiira** [comment]
PHP version should't effect it. Something is out of sync on your installation, the undefined makes me think it's your Atheos installation as I had to modify some core code to fix the marketplace.

I preformed another fresh install and haven't been able to replicate the issue

**Comment by clach04** [comment]
Just performed a fresh install, to a new directory (that way the browser isn't going to cache anything. That works (although it looked like I needed to refresh the browser window first).

ctrl-alt-b now works :-)

I found I can reset this instance with:

    rm -rf config.php data public ; mkdir data public ;  git checkout HEAD  data/README.md public/class.sourcemanager.php

and wiping out plugins. So I've tested the below the couple of times now.

However the click link on the right hand side of the blue plus is not working, console shows:

    Uncaught ReferenceError: addon is not defined
        openExternal http://192.168.11.85:82/atheos_issue_108/public/modules.min.js:289
        onclick http://192.168.11.85:82/atheos_issue_108/:1
    modules.min.js:289:1033

and the beautify  plugin still shows as something that can be installed (even though its working).
Clicking to attempt to install again says its installing and then corrupts the marketplace window, this is now blank/transparent even when reopened. The plugin still works BUT checking the plugin dir server side shows the 2nd install was Atheos-Beautify-master. E.g. after 1st install click:

    #  ls plugins/
    Beautify  README.md

after 2nd install of the same named Beautify  (i.e. not Atheos-Beautify).

    # ls plugins/
    Atheos-Beautify-master  Beautify  README.md

Happy to share any diags to figure this out.

**Comment by HLSiira** [comment]
Have you purged the plugin installation in /plugins?
The public folder is a minified version of those files, but unless you delete them, you might still be using a bad install of Beautify.
By default, Atheos should install the plugin without the Atheos- in front of it, so the Beautify is the best one.

I'll check out the plus buttons, see if something is missing. The addon is strange

**Comment by clach04** [comment]
Yes, purged plugins multiple times with this test :-) It was empty before the first click/install.

    rm -rf config.php data public plugins ; mkdir data public plugins ;  git checkout HEAD  data/README.md public/class.sourcemanager.php 

I can confirm that the Beautify plugin does NOT working untill refreshing the web browser after install so steps are:

1. `rm -rf config.php data public plugins ; mkdir data public plugins ;  git checkout HEAD  data/README.md public/class.sourcemanager.php `
1. setup/install
1. login
1. marketplace, install Beautify 
1. open test.js (already on file system) and alt-ctrl-b does NOT work
1. refresh web browser
1. open test.jsand alt-ctrl-b does now DOES work
1. marketplace, install Beautify again
1. plugin dir now has the two different Beautify  plugins present

**Comment by HLSiira** [comment]
Okay I know what the issue is. You are successfully installing Beautify twice, and it's causing all sorts of conflicting issues. The reason the marketplace doesn't reflect the newly installed plugin is because the marketplace addons/app list are cached as well, so they aren't rebuilt on every login. 

I'll need to make it so the cache is rebuilt when you install a plugin and that aught to fix the ability to reinstall the plugins.

The reason that there are two different named Beautify plugins is because the marketplace uses git clone to get the repo, then moves/renames that folder to the correct plugin name. If that folder already exists, then it fails.
