### ISSUE TITLE
Login issue with new installation

### ISSUE THREAD

**Issue by baddiedev** [Atheos/Atheos#115]
**Describe the bug**
After installing a fresh copy of Atheos on my website from Github today, I'm unable to log in for the first time. The setup process seemed to go ok. Config.php created and files in /data are all updated with user information. All files/folders in [the General Installation Guide](https://www.atheos.io/docs/installation) have write capabilities and my allow_url_fopen, ZIP, OPENSSL and MBSTRING are all enabled.

At the log in page, when I log in using the details I used during the setup, the page refreshes but I remain at the log in page being asked to log in. There are no login or system error messages.

**To Reproduce**
1. Download from Github as zip
2. Upload to website via ftp and extract
3. Navigate to URL of installation and complete first time setup
4. Attempt login with new details - issue occurs

**Expected behavior**
Log in to IDE

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 84.0.4147.127

**Additional context**
N/A

**Comment by WebCrew** [comment]
@HLSiira Here is my likewise "strange" idea about that strage issue :)

Did you also remove all jQuery requests requested via CDN from your script (if your script should contain them at all which I dont know at the moment)?

I  am asking because it is possible that the CDN hosted jQuery version, used for the website or script, might have been blocked **on the customer’s connection**. This type of issue is generally observed **on IP addresses** originating from countries like China, Indonesia, Korea, etc. Especially now that the times with China and Korea are extremely tense, it is quite possible that the CDNs have been banned and there is no longer any access to them.

**Comment by HLSiira** [comment]
That's a good thought but I don't have any CDN requests throughout all of Atheos. When you download it from Github, you should be getting the entire package, and your browser shouldn't be making any requests to external domains really. I'm going to have to comb through though, maybe I missed something critical in a json file somewhere or something.

**Comment by WebCrew** [comment]
I hope you`ll enjoy playing Sherlock Holmes :)

Good luck ;)
