### ISSUE TITLE
Terminal plugin stuck at Authentication Required; Enter Password:

### ISSUE THREAD

**Issue by Xehos** [Atheos/Atheos#146]
After opening terminal plugin and writing something in, I'm stuck at "Auth. required Enter Password:". Entering password does actually nothing. What should I do?

Screenshot
![Výstřižek](https://user-images.githubusercontent.com/26941193/102240355-0ca6c680-3ef8-11eb-8d0f-5741ce3fb2a0.PNG)

 - OS: Windows
 - Browser Firefox, Chrome
 - Server: Ubuntu 16.04, Atheos deployed in Docker

**Comment by HLSiira** [comment]
The password is "terminal" for default installations of the terminal plugin, and I believe it won't render the password as you type it similar to most consoles, but giving an error message will be added if it doesn't already have one.

Or it's a bug, I'll look into it but wanted to reply to you as soon as possible.

In case your curious: The idea for the password on the terminal plugin is that plugins are global, every user has access to all plugins installed, and since the terminal plugin is run as web user, a regular Atheos Read-Only user could do a lot of damage. So you need to both be authenticated with Atheos as well as be given the password (hopefully not default) by the admin of Atheos to use the terminal.

Let me know if that helps in the meantime, sorry you had to deal with this, I'm not sure how well documented it is currently.
