### ISSUE TITLE
Possibility to disable CodeGit

### ISSUE THREAD

**Issue by dododedodonl** [Atheos/Atheos#182]
On one of the systems I host Atheos, `exec` etc. are disabled, and I cannot enable them. This makes it, every so many seconds, an XHR request is done, resulting in a 500 error. This quite floods some log files, while this is expected behaviour.

Looking into this issue,  I also found an (semi related) issue: `PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable: code in components/codegit/traits/execute.php:15`

**Comment by HLSiira** [comment]
Well that must be beyond annoying. I'm finicky about my log files and that would drive me insane. I'm sorry about that, CodeGit didn't have a safety mechanism like the rest of Atheos uses. I modified CodeGit to use the correct execution function and gracefully handle errors better, hopefully that helps. I can look into a way to completely disable CodeGit safely, but it's supposed to just fail silently, since other components use one or two CodeGit functions from time to time.

Can you try the development branch and let me know how that goes?

**Comment by dododedodonl** [comment]
Yes, this solves the problem! Thank you for the quick looking into the issue, it is much appreciated! 😃 👍🏻
