### ISSUE TITLE
What is "Development Mode"?

### ISSUE THREAD

**Issue by wh33t** [Atheos/Atheos#264]
During initial install it offers this as a choice. What does this do?

**Comment by HLSiira** [comment]
Mainly, development mode disables the minimizing of Javascript files so it's easier to debug and trace lines, and enables quick access to the source code of Atheos from the project menu, so you can actually work on Atheos from within Atheos. It's been a long time since I've looked into what options I've built into that menu, but I believe it also enables a some more debug messages in the browser console, but don't quote me on that.

**Comment by wh33t** [comment]
Thank you.
