### ISSUE TITLE
Old version in settings

### ISSUE THREAD

**Issue by superkekko** [Atheos/Atheos#265]
Hi, I've installed the main branch but the version in the settings in the analytics didn't update.

![immagine](https://user-images.githubusercontent.com/25342565/226566718-1afb0b88-afa4-4ba9-96bc-667c274fee00.png)

**Comment by HLSiira** [comment]
Man that disabled button though lol

The versioning has never been something I was happy with until @N0tACyb0rg showed me Github Workflows. I've added a fix for it by turning it into a simple number, since I don't do semantic versioning anymore. Also changed the way it's stored and cleaned up the analytics for it as a result.
