### ISSUE TITLE
Marketplace updates

### ISSUE THREAD

**Issue by wolffe** [Atheos/Atheos#36]
Are you going to bring back some of the extensions or the plugins that Codiad used? Like SFTP or Git?

Is this an ongoing project? Do you intend to keep updating this project?

I've been looking for an alternative to Codiad for ages and now this IDE looks awesome. I'd like to code my own theme and maybe publish it here when it's done.

I am on PHP 7.4. Is there full support for PHP 7.4, as far as you know?

Thanks!

**Comment by HLSiira** [comment]
There is support for whatever bugs you bring to my attention lol. 

The **Codiad-CodeGit** does not work with Atheos, however I am maintaining my own **Atheos-CodeGit** fork that is being updated with Atheos, and I use it regularly to develop Atheos so it should work. However Atheos just got a huge rewrite that really affects how CodeGit operates and I might have missed a bug or two, but again, I can fix whatever I find.

I've never used the SFTP plugin, but I am doing my best to maintain backwards compatability with Codiad plugins, but some changes HAVE to be made to fix some other bugs. I suggest you download Atheos, let me know what doesn't work and I'll fix what I can. If you REALLY need the SFTP plugin or something else, let me know, I'll fork it and update it.

Another user just pushed a fix for PHP incompatibility with new versions, but I'm still on PHP7.0 (Just haven't updated yet) so I personally can't test whether it works but I don't see any reason why it shouldn't.

And yes, I'm going to be working on Atheos for a long time. For you're theme, I'm actually planning on eventually getting into using variables for all the CSS, so that the base Atheos theme will always be applied, and then the user can select a new theme that will be applied with the variables, so you don't need to reload the page to try a new theme, but that's a LONG LONG way down the road.

**Comment by wolffe** [comment]
Good to know. I've already installed it and played a bit with it. Looks good and fresh :)

I'll keep working more in the next weeks, as I got a bit out of habit and I'm using Atom.io now.

Thanks for your work!
