### ISSUE TITLE
How to manage users?

### ISSUE THREAD

**Issue by fsatzger** [Atheos/Atheos#57]
Atheos v4.0.1 

Can't find any user management? Is it implemented yet?

**Comment by fsatzger** [comment]
Configuration user from updating to Atheos v4.0.1 (user was no admin)

**Comment by HLSiira** [comment]
Mmmm weird. There should be a table that pivots the user data to a new file format but maybe something got lost in the sauce. If it happens again, please let me know, and in order to temp fix it while looking into it, ensure your admin user as Configure, Read, Write permissions.

Sorry about the bug.
