### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Merith-TK** [Atheos/Atheos#76]
![](https://i.imgur.com/es43pKc.png)
yeah... im on firefox dev

**Comment by HLSiira** [comment]
So the website works. https://www.atheos.io; however I must have messed up my DNS when setting up as it doesn't redirect to the www version of the url correctly, might not be just firefox. Let me see what I can do

**Comment by HLSiira** [comment]
Can you retest and verify it doesn't work? I changed somethings and it's worked on multiple variations now.

**Comment by Merith-TK** [comment]
works fine for me now.

**Comment by HLSiira** [comment]
Alright, cool. Thank you. Let me know if you run into any issues or having any suggestions.

**Comment by Merith-TK** [comment]
honestly i find the login screen quite... ahem... *sexy* for a login screen. especially that animation... SO SMOOTH HOLY SHIT

**Comment by HLSiira** [comment]
Thank you, that means a lot. My wife made the logo after she nailed my personal logo on https://www.siira.us

We were actually just going to start playing with the logo more since it doesn't look good as a favicon but it's not high on the priority list.

And the background has just been a labor of effort for quite a while now, I'm a huge fan of Hexagons. I can't take all credit though, I found the js for generating the actual hexagons on a github gist a while back.

It's actually a separate repo called Synthetic under my account, very easy to implement but I might have made some improvements that haven't made it to the master yet.

-------- Original Message --------

**Comment by Merith-TK** [comment]
still, very cool
